reject:
  # ILP-Packet <= v2.2.0 is required to support the ILP-Packet version used by the Mojaloop Specification v1.x.
  - "ilp-packet"
  # eslint-config-airbnb-base relies on eslint < 9.0.0
  - "eslint"
